language: node_js

node_js:
  - 8

install:
  - npm install
  - npm install -g codecov

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run report-coverage

env:
  - CI=true
  - CODECOV_TOKEN="44ada813-9ce4-48b9-a122-512cf7a99c2e"