language: node_js

node_js:
  - 8

install:
  - npm install
  - npm install -g codecov

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run report-coverage

env:
  global:
    - CODECOV_TOKEN="1063b2a2-6099-41d7-9161-6a13fe6011d8"